[project]
name = "upsidedownhorse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "upsidedownhorse", email = "tp0110@uah.edu" }
]
requires-python = ">=3.12"
dependencies = []

[tool.maturin]
module-name = "upsidedownhorse._core"
python-packages = ["upsidedownhorse"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
